/*selections for cricket_ff saved at 230724_194937*/
//:[1] (0)
( 'vol': 10.0, 'endframe': 979297, 'buf': 'cricket_ff', 'ampctl': [ 'tokyo', 'amp', 1, 'xyz', 0, 1, 'lin' ], 
  'paramctl': ( 'vol': [ 'tokyo', 'vol', 1, 'off', 0, 10, 'lin' ], 'trate': [ 'tokyo', 'trate', 1, 'z', 0.3, 0.9, 'lin' ], 'pos': [ 'tokyo', 'pos', 1, 'x', 0.22, 0.9, 'lin' ] ), 'startframe': 0, 'playfunc': 'grainharmonics', 'trate': 0.74285714285714, 'pos': 0.38214285714286 )
