/*selections for default saved at 230724_172152*/
//:[1] (0)
( 'vol': 1, 'endframe': 145975, 'trigger': 0, 'buf': 'default', 
'ampctl': [ 'tokyo', 'amp', 1, 'xyz', 0, 1, 'lin' ], 'paramctl': (
	'rate': [ 'tokyo', 'rate', 1, 'off', 0.01, 10, 'lin' ],
	'vol': [ 'tokyo', 'vol', 1, 'off', 0, 1, 'lin' ],
	'trigger': [ 'tokyo', 'trigger', 1, 'off', 0, 1, 'lin' ],
	'loop': [ 'tokyo', 'loop', 1, 'off', 0, 1, 'lin' ]
), 'loop': 0, 'rate': 1, 'startframe': 77365, 
'playfunc': 'phasebuf' )
