/*selections for default saved at 230725_111639*/
//: default phasebuf (0)
( 'vol': 1, 'endframe': 140377, 'buf': 'default', 'ampctl': [ 'tokyo', 'amp', 1, 'off', 0, 1, 'lin' ], 
  'paramctl': ( 'rate': [ 'tokyo', 'rate', 1, 'off', 0.01, 10, 'lin' ], 'vol': [ 'tokyo', 'vol', 1, 'off', 0, 10, 'lin' ] ), 'startframe': 88130, 'rate': 1, 'playfunc': 'phasebuf' )
//: default loopbuf (15)
( 'vol': 1, 'endframe': 173678, 'trigger': 0, 'buf': 'default', 
  'ampctl': [ 'tokyo', 'amp', 1, 'off', 0, 1, 'lin' ], 'paramctl': ( 'rate': [ 'tokyo', 'rate', 1, 'off', 0.01, 10, 'lin' ], 'vol': [ 'tokyo', 'vol', 1, 'off', 0, 1, 'lin' ], 'trigger': [ 'tokyo', 'trigger', 1, 'off', 0, 1, 'lin' ], 'loop': [ 'tokyo', 'loop', 1, 'off', 0, 1, 'lin' ] ), 'loop': 0, 'rate': 1, 'startframe': 156310, 
  'playfunc': 'loopbuf' )
