/*selections for default saved at 230725_111233*/
//: default (0)
( 'vol': 1, 'endframe': 171955, 'buf': 'default', 'ampctl': [ 'tokyo', 'amp', 1, 'off', 0, 1, 'lin' ], 
  'paramctl': ( 'rate': [ 'tokyo', 'rate', 1, 'off', 0.01, 10, 'lin' ], 'vol': [ 'tokyo', 'vol', 1, 'off', 0, 10, 'lin' ], 'trate': [ 'tokyo', 'trate', 1, 'off', 0, 1, 'lin' ], 'pos': [ 'tokyo', 'pos', 1, 'off', 0, 1, 'lin' ] ), 'startframe': 133775, 'rate': 1, 'playfunc': 'graintornado', 'trate': 0, 
  'pos': 0 )
//: default (10)
( 'vol': 1, 'endframe': 99613, 'buf': 'default', 'ampctl': [ 'tokyo', 'amp', 1, 'off', 0, 1, 'lin' ], 
  'paramctl': ( 'rate': [ 'tokyo', 'rate', 1, 'off', 0.01, 10, 'lin' ], 'vol': [ 'tokyo', 'vol', 1, 'off', 0, 10, 'lin' ], 'thresh': [ 'tokyo', 'thresh', 1, 'off', 0, 80, 'lin' ] ), 'startframe': 75212, 'rate': 1, 'thresh': 80, 'playfunc': 'magabove' )
