/*selections for bird_crickets saved at 230725_230547*/
//: bird_crickets grainfroth (0)
( 'selectionNum': 0, 'ampctl': [ 'tokyo', 'amp', 1, 'off', 0, 1, 'lin' ], 'startframe': 720884, 'trate': 0, 
  'pos': 0, 'player': 'tokyo', 'vol': 1, 'endframe': 909022, 'buf': 'bird_crickets', 
  'paramctl': ( 'vol': [ 'tokyo', 'vol', 1, 'off', 0, 10, 'lin' ], 'trate': [ 'tokyo', 'trate', 1, 'off', 0, 1, 'lin' ], 'pos': [ 'tokyo', 'pos', 1, 'off', 0, 1, 'lin' ] ), 'playfunc': 'grainfroth' )
