/*selections for bird_crickets saved at 230803_195029*/
//: bird_crickets grainfroth (0)
( 'selectionNum': 0, 'ampctl': [ 'tokyo', 'amp', 1, 'off', 0, 1, 'lin', "x.lag(1).exp(500, 1000)", "(1 - z.lag(1)).exp(500, 1000)", "(x + y + z).lag(1).exp(500, 1000)" ], 'startframe': 551374, 'trate': 0.0, 
  'pos': 0.15525114155251, 'player': 'tokyo', 'vol': 1, 'endframe': 1750985, 'buf': 'bird_crickets', 
  'paramctl': ( 'vol': [ 'tokyo', 'vol', 3, 'z', 0, 0.9, 'lin', "x.lag(1).exp(500, 1000)", "(1 - z.lag(1)).exp(500, 1000)", "(x + y + z).lag(1).exp(500, 1000)" ], 'trate': [ 'tokyo', 'trate', 4, 'x', 0.1, 0.4, 'lin', "x.lag(1).exp(500, 1000)", "(1 - z.lag(1)).exp(500, 1000)", "(x + y + z).lag(1).exp(500, 1000)" ], 'pos': [ 'tokyo', 'pos', 3, 'x', 0, 1, 'lin', "x.lag(1).exp(500, 1000)", "(1 - z.lag(1)).exp(500, 1000)", "(x + y + z).lag(1).exp(500, 1000)" ] ), 'playfunc': 'grainfroth' )
