/*selections for bird_crickets saved at 230730_155059*/
//: bird_crickets grainecho (0)
( 'dur': 1, 'selectionNum': 0, 'ampctl': [ 'asayo', 'amp', 2, 'xyz', 0, 1, 'lin', "x.lag(1).exp(500, 1000)", "(1 - z.lag(1)).exp(500, 1000)", "(x + y + z).lag(1).exp(500, 1000)" ], 'startframe': 447060, 
  'rate': 1, 'trate': 0, 'pos': 0, 'player': 'asayo', 'vol': 1, 
  'endframe': 2112359, 'buf': 'bird_crickets', 'paramctl': ( 'rate': [ 'asayo', 'rate', 2, 'z', 0.01, 10, 'lin', "x.lag(1).exp(500, 1000)", "(1 - z.lag(1)).exp(500, 1000)", "(x + y + z).lag(1).exp(500, 1000)" ], 'vol': [ 'asayo', 'vol', 1, 'off', 0, 10, 'lin', "x.lag(1).exp(500, 1000)", "(1 - z.lag(1)).exp(500, 1000)", "(x + y + z).lag(1).exp(500, 1000)" ], 'dur': [ 'asayo', 'dur', 2, 'x', 0, 1, 'lin', "x.lag(1).exp(500, 1000)", "(1 - z.lag(1)).exp(500, 1000)", "(x + y + z).lag(1).exp(500, 1000)" ], 'trate': [ 'asayo', 'trate', 1, 'off', 0, 1, 'lin', "x.lag(1).exp(500, 1000)", "(1 - z.lag(1)).exp(500, 1000)", "(x + y + z).lag(1).exp(500, 1000)" ], 
  'pos': [ 'asayo', 'pos', 1, 'off', 0, 1, 'lin', "x.lag(1).exp(500, 1000)", "(1 - z.lag(1)).exp(500, 1000)", "(x + y + z).lag(1).exp(500, 1000)" ] ), 'playfunc': 'grainecho' )
