#+TITLE: Izutsu Catalog_readme
25 Oct 2022 22:56

Catalog of sounds to build a vocabulary for the Izutsu piece.
Start by corresponding these sounds along with dance body movements
to any of the concepts listed below.
Then select some of these sounds to build scenes in the Izutsu piece.

* Actions, Dialog and Narrative Situations
** Narrative situations
The "Narrative situation" is the relatioship of an action or situation is described to the person who describes it in the performance / play. For example:

Direct relationship: The monk says "I am surprised at your beauty" - he refers to his state directly within the story that is told, at the moment that it is told on stage.

Indirect relationship:

- The Lady tells a story, and in that story, she tells a story to her husband. (a story in the story)
- In the story that the lady tells to her husband, the children exchange small stories in the form of poems. (A story in a story in the story.)

A person may refer to their state or something that they have done in the past.  They may may either refer to having done or experienced it directly hemselves, or refer to themselves as some other person.

Also the narrator may deny some fact, but offer hints to indicate that there is an alternative version which makes this fact true.  This is the case of The Lady saying "This man is now long dead. How can I possibly have known him?".  She is hinting that she actually has known him, because she is a being that lives across time.  (Her name "Aritsune", which means: "Having Persistence", indicates this.)

Another type disinction in he narrative situation is that of a real experience vs dream experience.  The actions in the stage may represent something supposed to be happening in the real world, or in a dream.

** Actions:

- prayer
- dance
- offering of flowers and water
- drawing water from the well
- writing or sending a letter
- combing hair
- comparing heights / playing

** List of most important elements and states to represent through sound and movement

- Water
- Moon
- Purity and clarity
- Loneliness
- Longing
- Impermanence vs Permanence
- Cyclical regeneration
- Reflection on the water
- Transfiguration to another person
- Woman of today vs woman of past times
- Children's play
- Passage to the Beyond, the Past, the World of the Dead
** Types of sounds or music structure to explore
*** Like water flowing and trickling in a brook
*** Like water rushing violently in a torrent
*** Like water falling in a waterfall
*** Rustling of leaves
*** Suzuran bells in the wind
*** Wind blowing softly
*** Wind blowing vehemently
... ?
